### ISSUE TITLE
Document hash functions

### ISSUE THREAD

**Issue by v0dro** [silverhammermba/emberb#12]
There are many functions that work directly on Hashes like `rb_hash_aref()`.

I can write a PR if you can tell me where the text is to go.

**Comment by silverhammermba** [comment]
I intentionally omitted such documentation. The Ruby headers are just too big: the resulting documentation would be massive and difficult to maintain as Ruby evolves.

And, for the most part, that stuff is easy to look up if you know how to look for it (which is what my guide intends to teach you). For example, look up the documentation for [Hash#[]](https://ruby-doc.org/core/Hash.html#method-i-5B-5D) and click the source: it shows you that the internal call is `rb_hash_aref` and how the parameters are used. The amount of value added by including such documentation in my guide doesn't seem worth it considering the work involved.

If you feel up to the task, I'd say make your own separate documentation project. Let me know about it and I will happily link to it from my guide.

**Comment by v0dro** [comment]
Ah ok. I'm considering adding it to the official ruby docs on ruby-doc.org.
See this issue: https://bugs.ruby-lang.org/issues/15074
