### ISSUE TITLE
Document interfacing with complex numbers

### ISSUE THREAD

**Issue by v0dro** [silverhammermba/emberb#15]
There almost zero documentation on complex numbers even in the README.EXT file in the Ruby sources (except the name of the file in which complex numbers are present).

Documenting this would be very very helpful.

**Comment by silverhammermba** [comment]
Is there any particular catch to Complex numbers? Taking a look at [intern.h](https://github.com/ruby/ruby/blob/trunk/include/ruby/intern.h), I see `rb_complex_new` and etc. Closing for the same reason as #12 but let me know if I should reopen.
