### ISSUE TITLE
Missing link for "when" in The Ruby C API

### ISSUE THREAD

**Issue by gemmaro** [silverhammermba/emberb#25]
Hello,

I noticed that there is no URL for the `[when]` reference on ["The Ruby C API"][c].
I looked in the Git history, and it seems that the link was missing from the beginning. Here is the first commit that adds this footnote:

[c]: https://silverhammermba.github.io/emberb/c/

https://github.com/silverhammermba/emberb/blob/7b0517595594d3ce0b5cc0dc904b760e5b53857a/_posts/2010-01-01-c.markdown?plain=1#L294-L297

Thank you.

**Comment by silverhammermba** [comment]
It's not a broken link, it was a bad way to indicate that I removed some words from the original quote. Replaced with ellipsis in 2f0f95b
