### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by ghost** [silverhammermba/emberb#3]
It seems obvious from the running website that you wish all this to be under: Creative Commons Attribution 4.0 International License.

However, it would be a good idea IMHO to have the license in a LICENSE file in the root of the repository so that people (like me) who were trying to make a pull request and wanted to know what license it was under have a more accessible place for this information.

**Comment by silverhammermba** [comment]
Good point. Fixed with f383106f8f4fad05072b18f8185d266e84341162
