### ISSUE TITLE
Explain how to build an extension with CMake

### ISSUE THREAD

**Issue by dfyx** [silverhammermba/emberb#4]
What the title says.

**Comment by silverhammermba** [comment]
I'm curious about why you want to do this. Mkmf is specifically designed for building Ruby extensions on any platform (and I think it's a requirement if you want to make a gem). What do you need cmake for?

**Comment by dfyx** [comment]
Just curious as there appear to be some extensions that do use cmake.

(Also, I have a cmake-powered project that currently uses libruby in a C++ executable but might soon be transformed into a gem)

**Comment by silverhammermba** [comment]
Interesting. Can you show me a specific example? I'm having a hard time finding one.

**Comment by dfyx** [comment]
Sadly I can't remember a specific one but I'm pretty sure there was at least one that had CMake as a compile time dependency. If I can find it again, I'll tell you.
