### ISSUE TITLE
Problem while running Ruby code from C

### ISSUE THREAD

**Issue by madgen** [silverhammermba/emberb#5]
After a clean compilation I get the following error when I try to run the compiled binary on OS X El Capitan.

```
dyld: lazy symbol binding failed: Symbol not found: _ruby_init
  Referenced from: /Users/user/p/c/playground/./a.out
  Expected in: flat namespace

dyld: Symbol not found: _ruby_init
  Referenced from: /Users/user/p/c/playground/./a.out
  Expected in: flat namespace

[1]    64228 trace trap  ./a.out
```

The compilation flags are as follows:

```
$ gcc call_ruby.c $(pkg-config --cflags --libs ruby-2.2)
```

And pkg-config evaluates to the following:

```
-I/Users/user/.rbenv/versions/2.2.2/include/ruby-2.2.0/x86_64-darwin15 -I/Users/user/.rbenv/versions/2.2.2/include/ruby-2.2.0 -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -lpthread -lgmp -ldl -lobjc
```

I tried to recompile Ruby as I upgraded OS version in the meantime, but didn't change anything.

**Comment by dmitry** [comment]
@madgen post a ruby and C code here :)

**Comment by silverhammermba** [comment]
Sorry for being insanely late seeing this. I don't have an OSX machine so I can't reproduce. But at a glance I don't see any `-lruby` for linking with the Ruby lib. That seems consistent with the missing symbol. I'm not sure why pkg-config doesn't pick that up.

**Comment by silverhammermba** [comment]
Years later and now I have an OSX machine. I still can't reproduce this sort of error. Check out the Makefiles from _test and _include in the repo: they work fine on OSX.
